juju:
  name: juju
  age: secret
  character: beautiful.smart.elegant

server:
  port: 8080

tomcat:
  max-connections: 10000
  max-http-post-size: 20MB
  max-threads: 200
  min-spare-threads: 10
  accept-count: 100
  accesslog:
    enabled: true

spring:
  application:
    name: juju-smart
  datasource:
    url: jdbc:mysql://172.20.177.39:3306/base_data?characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: basedata
    password: basedata
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 172.20.181.100
    port: 63791
    timeout: 1000ms
    password: 123456

hikari:
  max-lifetime: 28770000
  maximum-pool-size: 15
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  useLocalSessionState: true
  rewriteBatchedStatements: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false

mybatis:
  mapper-locations: classpath:mapper/*.xml









