server:
  port: 8080

tomcat:
  max-connections: 10000
  max-http-post-size: 20MB
  max-threads: 200
  min-spare-threads: 10
  accept-count: 100
  accesslog:
    enabled: true

spring:
  application:
    name: juju-smart
  datasource:
#    url: jdbc:mysql://172.20.177.39:3306/base_data?characterEncoding=utf8&characterSetResults=utf8&useSSL=false
#    username: basedata
#    password: basedata
    url: jdbc:mysql://10.211.55.6:3306/smart?characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: juju2
    password: Juju
    driver-class-name: com.mysql.cj.jdbc.Driver

hikari:
  max-lifetime: 28770000
  maximum-pool-size: 15
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  useLocalSessionState: true
  rewriteBatchedStatements: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false

mybatis:
  mapper-locations: classpath:mapper/*.xml







